blog_add:
    path:      /add
    defaults:
        _controller: BlogBundle:News:add

blog_view:
    path:      /view{id}
    defaults:
        _controller: BlogBundle:News:view

blog_del:
    path:      /del{id}
    defaults:
        _controller: BlogBundle:News:delete

blog_index:
    path:      /
    defaults:
        _controller: BlogBundle:News:index          

blog_list1:
    path:      /ff
    defaults:
        _controller: BlogBundle:News:list1       

blog_list2:
    path:      /index1
    defaults:
        _controller: BlogBundle:News:list1

blog_list3:
    path:      /index2
    defaults:
        _controller: BlogBundle:News:list1        
     

# dans /var/www/html/blogsymf1/app/config/routing.yml nous avons ceci
# blog_root:
#    resource: "@BlogBundle/Resources/config/routing.yml"
